name = "api-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "trading-db"
database_id = "f46447d4-9f14-45f5-bd5c-24f4635ebdbd"

[vars]
PERFORMANCE_MCP_URL = "https://performance-tracker-mcp.sahuankitaofc-1.workers.dev"
